### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by Croutful** [qwertyuiop3/Magic_Recode#1]
After starting and stopping a recording, the option to playback doesn't appear in the release version on UC, nor does the recorded path drawing work. I have no idea how to compile the code for the latest .dll, are you able to send to me?

**Comment by qwertyuiop3** [comment]
uc version is outdated software works only partially Copy_User_Command that is responsible for recording isn't called so nothing is being recorded

"7. Off-site linking is strictly forbidden unless you are linking to a website that explicitly relates to game cheating or the topic at hand. All small articles and all supportive content should be posted on this website (with credits to the author where applicable). Leeway is given for large content where posting on this website would be a very time consuming process. Permission must be granted by a community staff member before you are allowed to link to such content. Linking to websites that do not relate to the UnKnoWnCheaTs community's goal, that sell goods or services (including but not limited to cheats), that are referral links, surveys, generate revenue, or that violate any of the other community rules (i.e. external cheat downloads) is strictly prohibited."

leave me your contact information

**Comment by Croutful** [comment]
> uc version is outdated software works only partially Copy_User_Command that is responsible for recording isn't called so nothing is being recorded
> 
> "7. Off-site linking is strictly forbidden unless you are linking to a website that explicitly relates to game cheating or the topic at hand. All small articles and all supportive content should be posted on this website (with credits to the author where applicable). Leeway is given for large content where posting on this website would be a very time consuming process. Permission must be granted by a community staff member before you are allowed to link to such content. Linking to websites that do not relate to the UnKnoWnCheaTs community's goal, that sell goods or services (including but not limited to cheats), that are referral links, surveys, generate revenue, or that violate any of the other community rules (i.e. external cheat downloads) is strictly prohibited."
> 
> leave me your contact information

Oh ok, I see..
My discord is ID is 685736532996653212
or just Voxina#3276
