### ISSUE TITLE
build

### ISSUE THREAD

**Issue by fishlipz** [qwertyuiop3/Magic_Recode#5]
build not working can you add me on discord jz#8561

**Comment by qwertyuiop3** [comment]
late reply wasn't thinking about this project in past months as it's almost finished besides few unimportant things i probably will never do as this code seems alien and sometimes irrational to me now

1 -> CGameMovement::TryPlayerMove uses ray tracing with accountancy of bounding boxes to check if player collides with object determining its stop point
2 -> as of now ray angle is simply incrementary from 0 to 360 degree problem it causes is impossibility to limit it in your field of view; solution would be swapping signbit and using half of ray angle on every second iteration
3 -> optionally route visualization should be outlined for better visibility at cost of eight times greater scoped cycles consumption
4 -> long time ago when i was writing this project i had in mind minimizing memory consumption at cost of functionality but as of now i would probably save whole record despite it could consume megabytes or gigabytes of memory for sake of full compatibility with segmented recording

if someone is still interested in this project i wouldn't mind merging changes from listed above todos

also csgo version is outdated i don't maintain it anymore as there is no demand in it and submodules are slightly outdated

if you still need help tell me what operating system you're using and post compiler output publicly here so it may serve as help in future to others
